import { defineField, defineType } from 'sanity';

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  groups: [
    { name: 'homepage', title: 'Homepage preview', default: true },
    { name: 'story', title: 'About page' },
    { name: 'values', title: 'Values' },
    { name: 'cta', title: 'Call to action' },
    { name: 'seo', title: 'Search and sharing' },
  ],
  fields: [
    defineField({
      name: 'homeEyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'homepage',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'homeHeading',
      title: 'Heading',
      type: 'string',
      group: 'homepage',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'homeIntroduction',
      title: 'Introduction',
      type: 'text',
      rows: 4,
      group: 'homepage',
      validation: (Rule) => Rule.required().max(500),
    }),
    defineField({
      name: 'portrait',
      title: 'Portrait',
      type: 'image',
      group: ['homepage', 'story'],
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alternative Text',
          type: 'string',
          description: 'Briefly describe the photo for visitors using screen readers.',
          validation: (Rule) => Rule.max(160),
        }),
      ],
    }),
    defineField({
      name: 'heroEyebrow',
      title: 'Hero Eyebrow',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero Title',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'heroIntroduction',
      title: 'Hero Introduction',
      type: 'text',
      rows: 4,
      group: 'story',
      validation: (Rule) => Rule.required().max(600),
    }),
    defineField({
      name: 'storyEyebrow',
      title: 'Story Eyebrow',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'storyHeading',
      title: 'Story Heading',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'biography',
      title: 'Biography Paragraphs',
      type: 'array',
      group: 'story',
      of: [{ type: 'text', rows: 5, validation: (Rule) => Rule.required().max(1200) }],
      validation: (Rule) => Rule.required().min(1).max(6),
    }),
    defineField({
      name: 'valuesEyebrow',
      title: 'Values Eyebrow',
      type: 'string',
      group: 'values',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'valuesHeading',
      title: 'Values Heading',
      type: 'string',
      group: 'values',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'values',
      title: 'Values',
      type: 'array',
      group: 'values',
      of: [
        {
          type: 'object',
          name: 'aboutValue',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (Rule) => Rule.required().max(80),
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              rows: 3,
              validation: (Rule) => Rule.required().max(400),
            }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'description' },
          },
        },
      ],
      validation: (Rule) => Rule.required().min(1).max(3),
    }),
    defineField({
      name: 'ctaEyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'cta',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'ctaHeading',
      title: 'Heading',
      type: 'string',
      group: 'cta',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'ctaLabel',
      title: 'Button Label',
      type: 'string',
      group: 'cta',
      validation: (Rule) => Rule.required().max(50),
    }),
    defineField({
      name: 'seoTitle',
      title: 'Page Title',
      type: 'string',
      group: 'seo',
      description: 'Used in the browser tab and search results.',
      validation: (Rule) => Rule.required().max(70),
    }),
    defineField({
      name: 'seoDescription',
      title: 'Page Description',
      type: 'text',
      rows: 3,
      group: 'seo',
      validation: (Rule) => Rule.required().max(170),
    }),
  ],
  initialValue: {
    homeEyebrow: 'Meet the baker',
    homeHeading: '[Add a short heading about yourself]',
    homeIntroduction: '[Add a two or three sentence introduction about who you are, your background, and what you want customers to know about you.]',
    heroEyebrow: 'The story behind the sweets',
    heroTitle: 'About Star Sweets',
    heroIntroduction: '[Add a short introduction to your story and what Star Sweets means to you.]',
    storyEyebrow: 'Your introduction',
    storyHeading: '[Add your name or introduction heading]',
    biography: [
      '[Add your main biography here. You could include how you started baking, your professional background, and why you created Star Sweets.]',
      '[Add a second paragraph about your baking style, process, or what customers can expect when they order from you.]',
    ],
    valuesEyebrow: 'Your values',
    valuesHeading: '[Add a heading for what matters to you]',
    values: [
      { _key: 'value-one', title: '[First value]', description: '[Explain one principle that guides your work.]' },
      { _key: 'value-two', title: '[Second value]', description: '[Explain another part of your approach or service.]' },
      { _key: 'value-three', title: '[Third value]', description: '[Explain what customers can expect from you.]' },
    ],
    ctaEyebrow: "Let's make something memorable",
    ctaHeading: 'Ready to plan your cake?',
    ctaLabel: 'Start your order',
    seoTitle: 'About - Star Sweets',
    seoDescription: 'Meet the baker and owner behind the Star Sweets microbakery.',
  },
  preview: {
    prepare() {
      return {
        title: 'About Page',
        subtitle: 'Homepage preview and full About page',
      };
    },
  },
});
