import { defineField, defineType } from 'sanity';

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  groups: [
    { name: 'homepage', title: 'Homepage preview', default: true },
    { name: 'story', title: 'About page' },
    { name: 'values', title: 'Values' },
    { name: 'cta', title: 'Call to action' },
    { name: 'seo', title: 'Search and sharing' },
  ],
  fields: [
    defineField({
      name: 'homeEyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'homepage',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'homeHeading',
      title: 'Heading',
      type: 'string',
      group: 'homepage',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'homeIntroduction',
      title: 'Introduction',
      type: 'text',
      rows: 4,
      group: 'homepage',
      validation: (Rule) => Rule.required().max(500),
    }),
    defineField({
      name: 'portrait',
      title: 'Portrait',
      type: 'image',
      group: ['homepage', 'story'],
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alternative Text',
          type: 'string',
          description: 'Briefly describe the photo for visitors using screen readers.',
          validation: (Rule) => Rule.max(160),
        }),
      ],
    }),
    defineField({
      name: 'heroEyebrow',
      title: 'Hero Eyebrow',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero Title',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'heroIntroduction',
      title: 'Hero Introduction',
      type: 'text',
      rows: 4,
      group: 'story',
      validation: (Rule) => Rule.required().max(600),
    }),
    defineField({
      name: 'storyEyebrow',
      title: 'Story Eyebrow',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'storyHeading',
      title: 'Story Heading',
      type: 'string',
      group: 'story',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'biography',
      title: 'Biography Paragraphs',
      type: 'array',
      group: 'story',
      of: [{ type: 'text', rows: 5, validation: (Rule) => Rule.required().max(1200) }],
      validation: (Rule) => Rule.required().min(1).max(6),
    }),
    defineField({
      name: 'valuesEyebrow',
      title: 'Values Eyebrow',
      type: 'string',
      group: 'values',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'valuesHeading',
      title: 'Values Heading',
      type: 'string',
      group: 'values',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'values',
      title: 'Values',
      type: 'array',
      group: 'values',
      of: [
        {
          type: 'object',
          name: 'aboutValue',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (Rule) => Rule.required().max(80),
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              rows: 3,
              validation: (Rule) => Rule.required().max(400),
            }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'description' },
          },
        },
      ],
      validation: (Rule) => Rule.required().min(1).max(3),
    }),
    defineField({
      name: 'ctaEyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'cta',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'ctaHeading',
      title: 'Heading',
      type: 'string',
      group: 'cta',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'ctaLabel',
      title: 'Button Label',
      type: 'string',
      group: 'cta',
      validation: (Rule) => Rule.required().max(50),
    }),
    defineField({
      name: 'seoTitle',
      title: 'Page Title',
      type: 'string',
      group: 'seo',
      description: 'Used in the browser tab and search results.',
      validation: (Rule) => Rule.required().max(70),
    }),
    defineField({
      name: 'seoDescription',
      title: 'Page Description',
      type: 'text',
      rows: 3,
      group: 'seo',
      validation: (Rule) => Rule.required().max(170),
    }),
  ],
  initialValue: {
    homeEyebrow: 'Meet the baker',
    homeHeading: 'Emily',
    homeIntroduction: 'Emily is a 23 year old self-taught baker, food enthusiast, and dental student. She enjoys sharing her love of food, especially sweet treats, with friends, family, and everyone in between. She hopes to bring smiles to others from her kitchen and dental practice!',
    heroEyebrow: 'The story behind the sweets',
    heroTitle: 'About Star Sweets',
    heroIntroduction: '',
    storyEyebrow: 'Your introduction',
    storyHeading: 'Emily',
    biography: [
      'My first memory of baking was with my grandma as a young child making cookies together. My family has a tradition of baking box cakes for each of our birthdays, which inspired me to learn to bake them from scratch. I soon went on to teach myself everything I know now. My journey started in middle school and followed me all the way through university. I always loved baking for friends and family and showing my creativity through trying new recipes.',
      'During my last year in undergrad, I created Star Sweets as a way to spread my love for baking beyond my close circle. I wanted the opportunity to bring light to someone’s special day and make them feel like a star. While my studies have brought me to dental school, my passion for baking has only burned brighter and I can’t wait to see what it brings to my dental career.',
    ],
    valuesEyebrow: 'Your values',
    valuesHeading: '[Add a heading for what matters to you]',
    values: [
      { _key: 'value-one', title: 'There are no boundaries for imagination', description: 'Thinking outside the box is where uniqueness and creativity live. My goal for each cake is to stand apart and shine in their own way.' },
    ],
    ctaEyebrow: "Let's make something memorable",
    ctaHeading: 'Ready to plan your cake?',
    ctaLabel: 'Start your order',
    seoTitle: 'About - Star Sweets',
    seoDescription: 'Meet the baker and owner behind the Star Sweets microbakery.',
  },
  preview: {
    prepare() {
      return {
        title: 'About Page',
        subtitle: 'Homepage preview and full About page',
      };
    },
  },
});
